<div class="product-marketing">
    <div class="marketing-type"><span>Delivery above 1000</span><button>Free</button></div>
    <div class="marketing-type"><span>Cash on Delivery</span><button>Yes</button></div>
    <div class="marketing-type"><span>Free Photo Gift Tag!</span><button>Yes</button></div>

    <div class="marketing-details">
        <p>Greater NCR: 1-3 days, Major cities: 2-4 days, Province: 5-7 days. All in working days.</p>
    </div>
</div>
