<div class="payment-method">
        <p>
            <span>
                <img alt="" src="//www.toolnut.com/media/wysiwyg/icons/ico-visa.png">
            </span>
            <span>
                <img alt="" src="//www.toolnut.com/media/wysiwyg/icons/ico-mastercard.png">
            </span>
            <span><img alt="" src="//www.toolnut.com/media/wysiwyg/icons/ico-american-express.png">
            </span>
            <span>
                <img alt="" src="//www.toolnut.com/media/wysiwyg/icons/ico-discover-network.png">
            </span>
        </p>
    <div class="ship-to">
        <label>Ship to:</label>
        <div class="select"><span>Select a shipping address</span></div>
    </div>
</div>