<?php /** * Copyright © 2016 Magento. All rights reserved. * See COPYING.txt for license details. */
/** @var $block \Magento\Catalog\Block\Product\View */ ?>

<?php $_product = $block->getProduct(); ?><?php $buttonTitle = __('Add to Cart'); ?>

<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$StockState = $objectManager->get('\Magento\CatalogInventory\Api\StockStateInterface');
$prodQty =  $StockState->getStockQty($_product->getId(), $_product->getStore()->getWebsiteId());
?>

<?php if ($_product->isSaleable()): ?>
    <div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
            <div class="field qty"><label class="label" for="qty"><span><?php /* @escapeNotVerified */
                    echo __('Qty:') ?></span></label>

                <div class="control">
                    <a id="desc" class="quantity desc" href="javascript:void(0)">-</a>
                        <input type="number" name="qty" id="qty"
                            maxlength="12"
                            value="<?php /* @escapeNotVerified */
                            echo $block->getProductDefaultQty() * 1 ?>"
                            title="<?php /* @escapeNotVerified */
                            echo __('Qty') ?>"
                            class="input-text qty"
                            data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"/>
                    <a id="asc" class="quantity asc" href="javascript:void(0)">+</a>
                    <div class="quantity-count">
                        <span class="label">Estimate stocks:</span>
                        <span class="stock-qty">Low (Last <?php echo $prodQty ?> pieces left!)</span>
                    </div>
                </div>
            </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit" title="<?php /* @escapeNotVerified */
            echo $buttonTitle ?>" class="action primary tocart" id="product-addtocart-button">
                <span><?php /* @escapeNotVerified */
                    echo $buttonTitle ?></span></button> <?php echo $block->getChildHtml('', true) ?></div>
    </div></div><?php endif; ?>

    <script>
        //<![CDATA[
        require([
            'jquery'
        ], function ($) {
            'use strict';

            $('.quantity').on('click', function () {
                var $button = $(this);
                var oldValue = $button.closest('.control').find("#qty").val();

                if ($button.text() == "+") {
                    var newVal = parseFloat(oldValue) + 1;
                } else {
                    if (oldValue > 0) {
                        var newVal = parseFloat(oldValue) - 1;
                    } else {
                        newVal = 0;
                    }
                }
                $button.closest('.control').find("#qty").val(newVal);
            });
        });
        //]]>
    </script>

    <script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }

    </script><?php if (!$block->isRedirectToCartEnabled()) : ?>
    <script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "catalogAddToCart": {
                "bindSubmit": false
            }
        }
    }

    </script><?php endif; ?>